### ISSUE TITLE
Cannot login to the search page

### ISSUE THREAD

**Issue by Mestway** [Mestway/CmdReader#1]
After clicking "registration", I obtained a user name (but without password). But I cannot login to the search page with my user name, as the server told me "404 Not Found, The path '/index.html' was not found."

Can you add instructions how to login? Particularly, since there is no password required, can you delete the password field in the login page?

Thanks!

-Chenglong

**Comment by todpole3** [comment]
Sorry forgot to commit.

These should be resolved now.
